name = "backend-blog"
main = "src/index.ts"
compatibility_date = "2024-11-30"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZmUzZmM4NTUtYmY1Yi00ZmNmLWI1MGUtYjgwZDYyMTkxY2E3IiwidGVuYW50X2lkIjoiYzM3OTU5YjRlNTQwMjQ3ZWQ4YjEwYWJmMzY1ZjZlMDU4OTg4Zjk4ODlkNzQ5ZWYzNTBiZjE5ZWNmZDBmNDNmOCIsImludGVybmFsX3NlY3JldCI6IjI4MmM4ZmQxLTI1NzAtNDZlZi04ZWVhLWRkYTg2NTVkZjhmNSJ9.ziRHezL9PI7aF9YNKJOfthsOnx4XQHZGkh4L2GJuAGk"
JWT_SECRET = "mysecretkey"